# Generated by Django 3.0.8 on 2020-07-09 14:29

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[['new', 'new'], ['processing', 'processing'], ['needs_verify', 'needs_verify'], ['verified', 'verified'], ['error', 'error']], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('form_type', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='forms')),
                ('data', server.models.JSONField(default={})),
            ],
        ),
    ]
